name: PUBLISH

on:
  push:
    branches: [master]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout current repository to master branch
        uses: actions/checkout@v2

      - name: Setup NodeJs 14.x
        uses: actions/setup-node@v1
        with:
          node-version: "14.x"

      - name: Cache dependencies and build outputs to improve workflow execution time.
        uses: actions/cache@v1
        with:
          path: node_modules
          key: ${{ runner.os }}-js-${{ hashFiles('package-lock.json') }}

      - name: Install dependencies
        run: npm install

      - name: Publish to VSCode Marketplace
        run: vsce publish -p ${{ secrets.VSCE_TOKEN }}
